name: luci-app-internet-detector

on:
  workflow_dispatch:

env:
  REPO_SDK: https://mirror-01.infra.openwrt.org/releases/21.02.7/targets/ramips/mt7621/openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download sdk
        run: |
          wget ${REPO_SDK}
          tar xf openwrt-*
          rm -f *.tar.xz
          mv openwrt-* openwrt
          
      - name: Adjust location source
        run: |
          mv -f internet-detector openwrt/package/ && ls -a openwrt/package/
          mv -f luci-app-internet-detector openwrt/package/ && ls -a openwrt/package/
      
      - name: Updating feeds && Installing feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: Disable csstidy
        run: |
          cd openwrt/
          echo "# CONFIG_LUCI_CSSTIDY is not set" >> .config
      
      - name: Compile the source
        run: |
          mkdir -p packed
          cd openwrt/
          make defconfig
          make package/luci-app-internet-detector/compile -j${nproc} V=w
          find bin/ -type f -name '*internet-detector*' -exec mv -t ../packed {} +
         
      - name: Upload Package to Releases
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: generic
          artifacts: "packed/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
